-- 003_products_full.sql — Full product catalog for פרי לי
-- All prices in agorot (₪ × 100). Safe to re-run (ON CONFLICT DO NOTHING).
-- weight field: include 'ק״ג' → unit=kg, step=0.5. Otherwise unit, step=1.

-- ─── New categories ───────────────────────────────────────────────────────────
insert into categories (slug, name_he, sort_order) values
  ('boxes',       'קופסאות מתנה',  0),
  ('whole-fruit', 'פירות שלמים',   4),
  ('citrus',      'הדרים',         5),
  ('vegetables',  'ירקות',         6),
  ('extras',      'תוספות',        7)
on conflict (slug) do nothing;

-- ─── Products ─────────────────────────────────────────────────────────────────
with cat as (
  select id, slug as cslug from categories
)
insert into products
  (slug, name_he, name_en, category_id, kind,
   price_cents, weight, description_he, rating, reviews_count, tag, active)
values

  -- ── קופסאות מתנה ──────────────────────────────────────────────────────────
  ('box-couple',
   'קופסה זוגית מפנקת', 'Romantic Couple Box',
   (select id from cat where cslug='boxes'),
   'gift-box', 9000, 'קופסה',
   'פירות חתוכים ומעוצבים ברמה גבוהה לשניים. ❤️',
   4.9, 312, 'פופולרי', true),

  ('box-vip',
   'קופסת VIP מפוארת', 'VIP Luxury Box',
   (select id from cat where cslug='boxes'),
   'gift-box', 15000, 'קופסה',
   'מבחר פירות פרימיום חתוכים ומעוצבים. המוצר המפנק ביותר שלנו.',
   4.9, 187, 'פרימיום', true),

  ('box-vip-large',
   'קופסת VIP גדולה', 'VIP Large Box',
   (select id from cat where cslug='boxes'),
   'gift-box', 22000, 'קופסה גדולה',
   'מגוון גדול של פירות בעיצוב יוקרתי. מושלם לאירועים ומתנות.',
   4.8, 143, 'פרימיום', true),

  ('box-kids',
   'קופסת ילדים', 'Kids Box',
   (select id from cat where cslug='boxes'),
   'gift-box', 4500, 'קופסה',
   'פירות מתוקים, צבעוניים וחתוכים בצורה יפה לילדים. בריא וטעים!',
   4.8, 224, null, true),

  ('box-kids-large',
   'קופסת ילדים גדולה', 'Kids Large Box',
   (select id from cat where cslug='boxes'),
   'gift-box', 6000, 'קופסה גדולה',
   'מגוון פירות צבעוניים ומיוחדים לילדים — מספיק לכל הכיתה.',
   4.7, 98, null, true),

  ('box-health',
   'קופסת בריאות', 'Health Box',
   (select id from cat where cslug='boxes'),
   'gift-box', 8500, 'קופסה',
   'פירות טריים בשילוב תמרים ואגוזים. מקור מצוין לאנרגיה ואנטיאוקסידנטים.',
   4.8, 156, null, true),

  ('box-family',
   'קופסת אירוח משפחתית', 'Family Hosting Box',
   (select id from cat where cslug='boxes'),
   'gift-box', 12000, 'קופסה',
   'מבחר גדול של פירות חתוכים לאירוח. מספיק לכל המשפחה.',
   4.9, 201, null, true),

  ('box-premium-dates',
   'קופסת פרימיום עם תמרים ואגוזים', 'Premium Dates & Nuts Box',
   (select id from cat where cslug='boxes'),
   'gift-box', 16000, 'קופסה',
   'פירות מיוחדים עם תמרים מג׳הול ואגוזים מעורבים איכותיים.',
   4.9, 134, 'פרימיום', true),

  ('box-love',
   'קופסת LOVE זוגית', 'LOVE Couple Box',
   (select id from cat where cslug='boxes'),
   'gift-box', 13000, 'קופסה',
   'מארז רומנטי עם פירות ותמרים. מתנה מושלמת לאהובים.',
   4.9, 178, null, true),

  ('box-personal-can',
   'פחית פירות בעיצוב אישי', 'Personal Fruit Can',
   (select id from cat where cslug='boxes'),
   'gift-box', 2500, 'פחית',
   'פירות חתוכים ומעוצבים בתוך פחית יוקרת. עיצוב אישי לפי בחירה.',
   4.7, 89, 'חדש', true),

  -- ── פירות קלופים/חתוכים (מיכל 1 ק״ג) ────────────────────────────────────
  -- weight='מיכל' → unit=unit, step=1 (ordered by container)
  ('watermelon-cut',
   'אבטיח חתוך', 'Cut Watermelon',
   (select id from cat where cslug='peeled'),
   'watermelon', 5500, 'מיכל',
   'אבטיח מתוק, קלוף וחתוך לקוביות. נחתך ביום ההזמנה.',
   4.8, 203, null, true),

  ('melon-orange-cut',
   'מלון כתום חתוך', 'Cut Orange Melon',
   (select id from cat where cslug='peeled'),
   'melon', 5500, 'מיכל',
   'מלון כתום מתוק ועסיסי, קלוף וחתוך טרי.',
   4.7, 145, null, true),

  ('melon-green-cut',
   'מלון ירוק חתוך', 'Cut Green Melon',
   (select id from cat where cslug='peeled'),
   'melon', 5500, 'מיכל',
   'מלון ירוק מרענן, קלוף וחתוך. דיאטטי ומרענן.',
   4.7, 132, null, true),

  ('coconut-fresh',
   'קוקוס טרי חתוך', 'Fresh Coconut',
   (select id from cat where cslug='peeled'),
   'coconut', 6500, 'מיכל',
   'קוקוס טרי קלוף וחתוך. עשיר בסיבים ושומנים בריאים.',
   4.6, 67, null, true),

  ('strawberry-cut',
   'תות שדה חתוך', 'Cut Strawberries',
   (select id from cat where cslug='peeled'),
   'strawberry', 7500, 'מיכל',
   'תותים טריים וטעימים, שטופים ומוכנים לאכילה.',
   4.9, 289, null, true),

  ('grape-green-washed',
   'ענבים ירוקים שטופים', 'Washed Green Grapes',
   (select id from cat where cslug='peeled'),
   'grape-green', 6500, 'מיכל',
   'ענבים ירוקים חסרי גרעינים, שטופים ומוכנים לאכילה.',
   4.7, 178, null, true),

  ('grape-black-washed',
   'ענבים שחורים שטופים', 'Washed Black Grapes',
   (select id from cat where cslug='peeled'),
   'grape-black', 6500, 'מיכל',
   'ענבים שחורים מתוקים, שטופים ומוכנים לאכילה.',
   4.7, 156, null, true),

  ('mango-cut',
   'מנגו חתוך', 'Cut Mango',
   (select id from cat where cslug='peeled'),
   'mango', 7500, 'מיכל',
   'מנגו ארומטי ועשיר, קלוף וחתוך לפרוסות.',
   4.9, 234, null, true),

  ('kiwi-peeled',
   'קיווי מקולף', 'Peeled Kiwi',
   (select id from cat where cslug='peeled'),
   'kiwi', 6000, 'מיכל',
   'קיווי ירוק עשיר בוויטמין C, מקולף ופרוס.',
   4.6, 112, null, true),

  ('apple-red-cut',
   'תפוח אדום חתוך', 'Cut Red Apple',
   (select id from cat where cslug='peeled'),
   'apple', 5500, 'מיכל',
   'תפוח אדום קריספי וטרי, חתוך לפלחים.',
   4.5, 98, null, true),

  ('apple-green-cut',
   'תפוח ירוק חתוך', 'Cut Green Apple',
   (select id from cat where cslug='peeled'),
   'apple', 5500, 'מיכל',
   'תפוח ירוק חמצמץ וטרי, חתוך לפלחים.',
   4.5, 87, null, true),

  ('pear-cut',
   'אגס חתוך', 'Cut Pear',
   (select id from cat where cslug='peeled'),
   'pear', 5500, 'מיכל',
   'אגס מתוק וטרי, קלוף וחתוך לפרוסות.',
   4.6, 76, null, true),

  ('peach-cut',
   'אפרסק חתוך', 'Cut Peach',
   (select id from cat where cslug='peeled'),
   'peach', 6000, 'מיכל',
   'אפרסק בשל ועסיסי, קלוף וחתוך. עונתי!',
   4.7, 134, 'עונתי', true),

  ('nectarine-cut',
   'נקטרינה חתוכה', 'Cut Nectarine',
   (select id from cat where cslug='peeled'),
   'nectarine', 6000, 'מיכל',
   'נקטרינה מתוקה ועסיסית, חתוכה ומוכנה לאכילה.',
   4.7, 112, null, true),

  ('plum-cut',
   'שזיף חתוך', 'Cut Plum',
   (select id from cat where cslug='peeled'),
   'plum', 6000, 'מיכל',
   'שזיף אדום בשל ומתוק, חתוך לפרוסות.',
   4.6, 89, null, true),

  ('apricot-cut',
   'משמש חתוך', 'Cut Apricot',
   (select id from cat where cslug='peeled'),
   'apricot', 6000, 'מיכל',
   'משמש כתום ומתוק, קלוף וחתוך. עשיר בברזל.',
   4.6, 78, null, true),

  ('pomegranate-ready',
   'רימון מוכן לאכילה', 'Ready Pomegranate',
   (select id from cat where cslug='peeled'),
   'pomegranate', 7500, 'מיכל',
   'גרגירי רימון מופרדים ומוכנים לאכילה. ללא מאמץ!',
   4.8, 167, null, true),

  ('pomelo-peeled',
   'פומלה קלופה', 'Peeled Pomelo',
   (select id from cat where cslug='peeled'),
   'pomelo', 7000, 'מיכל',
   'פומלה מתוקה, קלופה ומחולקת לפלחים. פרי חורף מרענן.',
   4.7, 98, null, true),

  ('grapefruit-red-peeled',
   'אשכולית אדומה קלופה', 'Peeled Red Grapefruit',
   (select id from cat where cslug='peeled'),
   'orange', 6500, 'מיכל',
   'אשכולית אדומה מתוקה-חמצמצת, קלופה לפלחים.',
   4.6, 87, null, true),

  ('orange-peeled',
   'תפוז מקולף', 'Peeled Orange',
   (select id from cat where cslug='peeled'),
   'orange', 6000, 'מיכל',
   'תפוז מתוק ועסיסי, מקולף ומחולק לפרוסות.',
   4.7, 143, null, true),

  ('clementine-peeled',
   'קלמנטינות קלופות', 'Peeled Clementines',
   (select id from cat where cslug='peeled'),
   'orange', 6000, 'מיכל',
   'קלמנטינות מתוקות, מקולפות ומוכנות לאכילה.',
   4.8, 198, null, true),

  ('passion-fruit-ready',
   'פסיפלורה מוכנה', 'Ready Passion Fruit',
   (select id from cat where cslug='peeled'),
   'passion-fruit', 8000, 'מיכל',
   'פסיפלורה טרופית ואקזוטית, מוכנה לאכילה ישירה.',
   4.7, 56, null, true),

  ('lychee-peeled',
   'ליצ׳י קלוף', 'Peeled Lychee',
   (select id from cat where cslug='peeled'),
   'lychee', 8000, 'מיכל',
   'ליצ׳י טרופי מתוק ועסיסי, קלוף ומוכן לאכילה.',
   4.8, 89, null, true),

  ('banana-cut',
   'בננה חתוכה', 'Cut Banana',
   (select id from cat where cslug='peeled'),
   'banana', 5000, 'מיכל',
   'בננה בשלה וקרמית, חתוכה לפרוסות.',
   4.5, 76, null, true),

  ('mixed-premium',
   'פירות מעורבים פרימיום', 'Premium Mixed Fruits',
   (select id from cat where cslug='peeled'),
   'mixed-salad', 8000, 'מיכל',
   'תערובת מגוון הפירות הטריים שלנו — הפרימיום שבפרימיום.',
   4.9, 312, 'פרימיום', true),

  -- ── תוספות ────────────────────────────────────────────────────────────────
  ('extra-chocolate',
   'שוקולד בלגי', 'Belgian Chocolate',
   (select id from cat where cslug='extras'),
   'extra', 1500, 'יחידה',
   'שוקולד בלגי איכותי לטבילת פירות.',
   4.9, 89, null, true),

  ('extra-nuts',
   'אגוזים מעורבים', 'Mixed Nuts',
   (select id from cat where cslug='extras'),
   'extra', 1000, 'יחידה',
   'אגוזים מעורבים טריים — שקדים, קשיו, אגוזי מלך.',
   4.8, 67, null, true),

  ('extra-fruit-sushi',
   'סושי פירות', 'Fruit Sushi',
   (select id from cat where cslug='extras'),
   'extra', 2500, 'יחידה',
   'גלילות פירות בסגנון סושי יפני. ייחודי וטעים.',
   4.9, 134, 'חדש', true),

  ('extra-gift-wrap',
   'אריזת מתנה', 'Gift Wrap',
   (select id from cat where cslug='extras'),
   'extra', 1500, 'יחידה',
   'אריזת מתנה יוקרתית עם סרט וכרטיס ברכה.',
   4.8, 45, null, true),

  -- ── ירקות ─────────────────────────────────────────────────────────────────
  -- weight='ק״ג' → unit=kg, step=0.5 | weight='צרור'/'יחידה' → unit=unit, step=1
  ('zucchini',
   'קישואים', 'Zucchini',
   (select id from cat where cslug='vegetables'),
   'cucumber', 1800, 'ק״ג',
   'קישואים ירוקים טריים מהשדה.', 4.6, 45, null, true),

  ('eggplant',
   'חצילים', 'Eggplant',
   (select id from cat where cslug='vegetables'),
   'eggplant', 1500, 'ק״ג',
   'חצילים שחורים ורכים, מושלמים לצלייה.', 4.5, 38, null, true),

  ('cucumber-veg',
   'מלפפון', 'Cucumber',
   (select id from cat where cslug='vegetables'),
   'cucumber', 1300, 'ק״ג',
   'מלפפון פרסי קריספי וטרי.', 4.7, 87, null, true),

  ('tomato-veg',
   'עגבניה', 'Tomato',
   (select id from cat where cslug='vegetables'),
   'tomato', 1400, 'ק״ג',
   'עגבניות אדומות בשלות מהשדה.', 4.7, 76, null, true),

  ('potato-red',
   'תפוח אדמה אדום', 'Red Potato',
   (select id from cat where cslug='vegetables'),
   'potato', 1000, 'ק״ג',
   'תפוחי אדמה אדומים — מושלמים לאפייה.', 4.5, 43, null, true),

  ('onion-white',
   'בצל לבן', 'White Onion',
   (select id from cat where cslug='vegetables'),
   'onion', 1000, 'ק״ג',
   'בצל לבן מתוק לסלטים ולבישול.', 4.5, 34, null, true),

  ('onion-purple',
   'בצל סגול', 'Purple Onion',
   (select id from cat where cslug='vegetables'),
   'onion', 1200, 'ק״ג',
   'בצל סגול חד ומעניין, מוסיף צבע לכל מנה.', 4.5, 28, null, true),

  ('onion-green',
   'בצל ירוק', 'Green Onion',
   (select id from cat where cslug='vegetables'),
   'onion', 800, 'צרור',
   'בצל ירוק טרי — מעולה לסלטים ולקישוט.', 4.6, 56, null, true),

  ('carrot',
   'גזר', 'Carrot',
   (select id from cat where cslug='vegetables'),
   'carrot', 900, 'ק״ג',
   'גזרים כתומים מתוקים ועסיסיים.', 4.7, 67, null, true),

  ('pepper-red-veg',
   'גמבה אדומה', 'Red Bell Pepper',
   (select id from cat where cslug='vegetables'),
   'pepper', 2000, 'ק״ג',
   'פלפל אדום מתוק ועשיר בוויטמין C.', 4.6, 48, null, true),

  ('pepper-green-veg',
   'גמבה ירוקה', 'Green Bell Pepper',
   (select id from cat where cslug='vegetables'),
   'pepper', 1500, 'ק״ג',
   'פלפל ירוק פריך ורענן.', 4.5, 37, null, true),

  ('pepper-yellow-veg',
   'גמבה צהובה', 'Yellow Bell Pepper',
   (select id from cat where cslug='vegetables'),
   'pepper', 2000, 'ק״ג',
   'פלפל צהוב מתוק ועדין.', 4.6, 42, null, true),

  ('cabbage-white',
   'כרוב לבן', 'White Cabbage',
   (select id from cat where cslug='vegetables'),
   'cabbage', 900, 'ק״ג',
   'כרוב לבן פריך — מצוין לסלט קולסלאו.', 4.4, 29, null, true),

  ('cabbage-purple',
   'כרוב סגול', 'Purple Cabbage',
   (select id from cat where cslug='vegetables'),
   'cabbage', 1200, 'ק״ג',
   'כרוב סגול צבעוני, מוסיף עניין לכל סלט.', 4.5, 23, null, true),

  ('garlic-dry',
   'שום יבש', 'Dry Garlic',
   (select id from cat where cslug='vegetables'),
   'garlic', 3500, 'ק״ג',
   'שום יבש ריחני ועז. חיוני לכל מטבח.', 4.7, 54, null, true),

  ('garlic-fresh',
   'שום טרי', 'Fresh Garlic',
   (select id from cat where cslug='vegetables'),
   'garlic', 4500, 'ק״ג',
   'שום טרי ועסיסי — עז וריחני.', 4.7, 41, null, true),

  ('leek',
   'פרסה', 'Leek',
   (select id from cat where cslug='vegetables'),
   'leek', 1200, 'ק״ג',
   'פרסה ירוקה עדינה — לבישול ולסלטים.', 4.5, 31, null, true),

  ('potato-white',
   'תפוח אדמה לבן', 'White Potato',
   (select id from cat where cslug='vegetables'),
   'potato', 1000, 'ק״ג',
   'תפוחי אדמה לבנים לכל מטרה.', 4.5, 48, null, true),

  ('parsley',
   'פטרוזיליה', 'Parsley',
   (select id from cat where cslug='vegetables'),
   'herb', 600, 'צרור',
   'פטרוזיליה טרייה ירוקה — לקישוט ולתיבול.', 4.6, 34, null, true),

  ('coriander',
   'כוסברה', 'Coriander',
   (select id from cat where cslug='vegetables'),
   'herb', 600, 'צרור',
   'כוסברה ריחנית טרייה.', 4.5, 28, null, true),

  ('dill',
   'שמיר', 'Dill',
   (select id from cat where cslug='vegetables'),
   'herb', 600, 'צרור',
   'שמיר טרי ועדין לדגים ולסלטים.', 4.5, 22, null, true),

  ('mint',
   'נענע', 'Mint',
   (select id from cat where cslug='vegetables'),
   'herb', 600, 'צרור',
   'נענע טרייה ומרעננת — למשקאות ולסלטים.', 4.7, 45, null, true),

  ('celery-head',
   'ראש סלרי', 'Celery Root',
   (select id from cat where cslug='vegetables'),
   'herb', 1500, 'יחידה',
   'ראש סלרי שלם, מצוין למרקים וצלייה.', 4.5, 27, null, true),

  ('celery-stalk',
   'כרפס', 'Celery Stalks',
   (select id from cat where cslug='vegetables'),
   'herb', 1000, 'צרור',
   'כרפס טרי ופריך — לאכילה ישירה ולבישול.', 4.5, 31, null, true),

  ('beet',
   'סלק אדום', 'Red Beet',
   (select id from cat where cslug='vegetables'),
   'beet', 1200, 'ק״ג',
   'סלק אדום עשיר בברזל ובנוגדי חמצון.', 4.6, 38, null, true),

  ('turnip',
   'לפת', 'Turnip',
   (select id from cat where cslug='vegetables'),
   'root', 1200, 'ק״ג',
   'לפת לבנה-סגולה — קלאסיקה של הירקות הלבנטינים.', 4.4, 19, null, true),

  ('kohlrabi',
   'כולרבי', 'Kohlrabi',
   (select id from cat where cslug='vegetables'),
   'root', 1500, 'ק״ג',
   'כולרבי ירוק פריך, מצוין לאכילה גולמית.', 4.5, 24, null, true),

  ('radish',
   'צנון', 'Radish',
   (select id from cat where cslug='vegetables'),
   'root', 1200, 'ק״ג',
   'צנון לבן חד ופריך.', 4.4, 21, null, true),

  ('radish-small',
   'צנוניות', 'Cherry Radish',
   (select id from cat where cslug='vegetables'),
   'root', 1200, 'צרור',
   'צנוניות אדומות קטנטנות, מושלמות לסלטים.', 4.6, 34, null, true),

  ('corn',
   'תירס', 'Corn',
   (select id from cat where cslug='vegetables'),
   'corn', 400, 'יחידה',
   'תירס מתוק טרי — לבישול, לאפייה או לגריל.', 4.7, 67, null, true),

  -- ── הדרים ─────────────────────────────────────────────────────────────────
  ('orange-chinese',
   'תפוז סיני', 'Chinese Orange',
   (select id from cat where cslug='citrus'),
   'orange', 1500, 'ק״ג',
   'תפוז סיני מתוק ועסיסי.', 4.6, 54, null, true),

  ('orange-whole',
   'תפוזים', 'Oranges',
   (select id from cat where cslug='citrus'),
   'orange', 1200, 'ק״ג',
   'תפוזים עסיסיים ומתוקים, עשירים בוויטמין C.', 4.7, 89, null, true),

  ('grapefruit-whole',
   'אשכוליות', 'Grapefruit',
   (select id from cat where cslug='citrus'),
   'orange', 1400, 'ק״ג',
   'אשכוליות חמצמצות-מתוקות, מרעננות ובריאות.', 4.5, 47, null, true),

  ('lemon-whole',
   'לימונים', 'Lemons',
   (select id from cat where cslug='citrus'),
   'lemon', 1400, 'ק״ג',
   'לימונים עסיסיים לשימוש בבישול ובמשקאות.', 4.6, 56, null, true),

  ('clementine-whole',
   'קלמנטינות', 'Clementines',
   (select id from cat where cslug='citrus'),
   'orange', 1600, 'ק״ג',
   'קלמנטינות מתוקות קלות לקילוף — חטיף מושלם.', 4.8, 112, null, true),

  ('pomelo-whole',
   'פומלה', 'Pomelo',
   (select id from cat where cslug='citrus'),
   'pomelo', 2200, 'יחידה',
   'פומלה גדולה ומתוקה — פרי חורף מרשים.', 4.6, 43, null, true),

  ('pomelo-small-whole',
   'פומלית', 'Small Pomelo',
   (select id from cat where cslug='citrus'),
   'pomelo', 1800, 'יחידה',
   'פומלית קטנה וטעימה.', 4.5, 28, null, true),

  -- ── פירות שלמים ───────────────────────────────────────────────────────────
  ('strawberry-whole',
   'תותים', 'Strawberries',
   (select id from cat where cslug='whole-fruit'),
   'strawberry', 3000, 'ק״ג',
   'תותים אדומים ומתוקים — מהשדה ישירות אליך.', 4.9, 167, 'עונתי', true),

  ('mango-whole',
   'מנגו', 'Mango',
   (select id from cat where cslug='whole-fruit'),
   'mango', 2500, 'יחידה',
   'מנגו בשל וריחני, מגיע בשיאו.', 4.9, 134, null, true),

  ('fig-whole',
   'תאנים', 'Figs',
   (select id from cat where cslug='whole-fruit'),
   'fig', 3500, 'ק״ג',
   'תאנים סגולות בשלות ומתוקות. פרי הקיץ הישראלי.', 4.8, 89, 'עונתי', true),

  ('blueberry-whole',
   'אוכמניות', 'Blueberries',
   (select id from cat where cslug='whole-fruit'),
   'blueberry', 4000, 'יחידה',
   'אוכמניות טריות עשירות בנוגדי חמצון.', 4.8, 78, 'פרימיום', true),

  ('raspberry-whole',
   'פטל', 'Raspberries',
   (select id from cat where cslug='whole-fruit'),
   'berry', 3500, 'יחידה',
   'פטל עדין ומתוק, מצוין לקינוחים.', 4.7, 56, null, true),

  ('peach-whole',
   'אפרסקים', 'Peaches',
   (select id from cat where cslug='whole-fruit'),
   'peach', 2000, 'ק״ג',
   'אפרסקים בשלים ועסיסיים — ריח הקיץ.', 4.7, 98, 'עונתי', true),

  ('apricot-whole',
   'מישמיש', 'Apricots',
   (select id from cat where cslug='whole-fruit'),
   'apricot', 2500, 'ק״ג',
   'משמשים כתומים ומתוקים, עשירים בברזל.', 4.6, 67, 'עונתי', true),

  ('nectarine-white',
   'נקטרינה לבנה', 'White Nectarine',
   (select id from cat where cslug='whole-fruit'),
   'nectarine', 2500, 'ק״ג',
   'נקטרינה לבנה עדינה ומתוקה.', 4.7, 54, null, true),

  ('nectarine-yellow',
   'נקטרינה צהובה', 'Yellow Nectarine',
   (select id from cat where cslug='whole-fruit'),
   'nectarine', 2500, 'ק״ג',
   'נקטרינה צהובה עסיסית ומתוקה.', 4.7, 61, null, true),

  ('cherry-red',
   'דובדבנים אדומים', 'Red Cherries',
   (select id from cat where cslug='whole-fruit'),
   'cherry', 4500, 'ק״ג',
   'דובדבנים אדומים כהים, בשלים ומתוקים. עונתיים!', 4.9, 143, 'עונתי', true),

  ('guava-whole',
   'גויבה', 'Guava',
   (select id from cat where cslug='whole-fruit'),
   'guava', 2500, 'ק״ג',
   'גויבה טרופית ריחנית — טעם שמזכיר גן עדן.', 4.7, 45, null, true),

  ('pomegranate-whole',
   'רימונים', 'Pomegranates',
   (select id from cat where cslug='whole-fruit'),
   'pomegranate', 1500, 'יחידה',
   'רימונים אדומים עשירים — סמל הברכה.', 4.8, 112, null, true),

  ('cactus-pear-whole',
   'סברס', 'Cactus Pear',
   (select id from cat where cslug='whole-fruit'),
   'cactus-pear', 1800, 'ק״ג',
   'סברס ישראלי אמיתי — מתוק ומרענן.', 4.7, 67, 'עונתי', true),

  ('lychee-whole',
   'ליצי', 'Lychee',
   (select id from cat where cslug='whole-fruit'),
   'lychee', 4000, 'ק״ג',
   'ליצי טרופי מתוק — אקזוטי ומיוחד.', 4.8, 56, null, true),

  ('apple-hermon',
   'תפוח עץ חרמון', 'Hermon Apple',
   (select id from cat where cslug='whole-fruit'),
   'apple', 1800, 'ק״ג',
   'תפוח חרמון ישראלי — מתוק ופריך.', 4.7, 89, null, true),

  ('apple-grand-smith',
   'תפוח עץ גרנד סמיט', 'Granny Smith Apple',
   (select id from cat where cslug='whole-fruit'),
   'apple', 2200, 'ק״ג',
   'תפוח גרנד סמיט ירוק וחמצמץ — האהוב על הילדים.', 4.8, 134, null, true),

  ('apple-grand',
   'תפוח עץ גרנד', 'Grand Apple',
   (select id from cat where cslug='whole-fruit'),
   'apple', 2000, 'ק״ג',
   'תפוח גרנד אדום-גדול ועסיסי.', 4.7, 78, null, true),

  ('apple-jonathan',
   'תפוח עץ יונתן', 'Jonathan Apple',
   (select id from cat where cslug='whole-fruit'),
   'apple', 1600, 'ק״ג',
   'תפוח יונתן קלאסי — מזן ישראלי מוכח.', 4.6, 65, null, true),

  ('apple-pink-lady',
   'תפוח עץ פינק לידי', 'Pink Lady Apple',
   (select id from cat where cslug='whole-fruit'),
   'apple', 2200, 'ק״ג',
   'פינק לידי — מתוק ופריך. הפרמיום של התפוחים.', 4.9, 145, 'פרימיום', true),

  ('plum-red-whole',
   'שזיפ אדום', 'Red Plum',
   (select id from cat where cslug='whole-fruit'),
   'plum', 2500, 'ק״ג',
   'שזיפ אדום בשל ועסיסי.', 4.6, 54, null, true),

  ('plum-white-whole',
   'שזיפ לבן', 'White Plum',
   (select id from cat where cslug='whole-fruit'),
   'plum', 2800, 'ק״ג',
   'שזיפ לבן עדין ומתוק — נדיר ומיוחד.', 4.7, 38, null, true),

  ('cherry-white',
   'דובדבן לבן', 'White Cherry',
   (select id from cat where cslug='whole-fruit'),
   'cherry', 5500, 'ק״ג',
   'דובדבן לבן עדין ומתוק — נדיר ומבוקש.', 4.9, 67, 'פרימיום', true)

on conflict (slug) do nothing;
